In [ ]:
import torch
import numpy as np

## 1. Creating a tensor of some specific datatype

In [ ]:
tensor = torch.tensor([1.0,2.0,3.0])
tensor.dtype # Defaults to float32 in PyTorch

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

## 2. Knowing on which device the tensor is

In [ ]:
tensor = torch.randn(2,3)
tensor

tensor([[-0.1978,  0.1912,  0.5673],
        [ 0.8756, -1.2149, -0.5639]])

In [ ]:
tensor.device

device(type='cpu')

## 3. Permute -> Changing the order of the image dimensions in an image tensor

In [ ]:
image_tensor = torch.randn(32,32,3) # Generally some images are in this format: Colot channels last
image_tensor.shape

torch.Size([32, 32, 3])

In [ ]:
permuted_image_tensor = torch.permute(image_tensor,(2,0,1)) # However, the default in PyTorch is color channels first
permuted_image_tensor.shape

torch.Size([3, 32, 32])

## 4. Reshaping a torch tensor to the required shape

In [ ]:
random_tensor = torch.randn(3,3)
random_tensor,random_tensor.shape

(tensor([[-0.1183,  1.1098,  0.6249],
         [ 0.8910, -1.2645,  0.6519],
         [-0.8324,  0.3785, -0.2300]]),
 torch.Size([3, 3]))

In [ ]:
# However assume that we need this in a shape [1,3,3]
# We can use unsqueeze or reshape
reshaped_random_tensor = random_tensor.reshape(1,3,3)
reshaped_random_tensor,reshaped_random_tensor.shape

(tensor([[[-0.1183,  1.1098,  0.6249],
          [ 0.8910, -1.2645,  0.6519],
          [-0.8324,  0.3785, -0.2300]]]),
 torch.Size([1, 3, 3]))

## 5. Converting a numpy array into a tensor and vice versa

In [ ]:
numpy_array = np.random.randn(2,2)
numpy_array

array([[-0.94615234, -0.20137592],
       [ 0.93020961,  0.1082124 ]])

In [ ]:
# Converting numpy_array into a tensor
tensor = torch.from_numpy(numpy_array)
tensor

tensor([[-0.9462, -0.2014],
        [ 0.9302,  0.1082]], dtype=torch.float64)

However, it is important to note that when we cave created a numpy array, it defaults to creating a numpy array with elements of default datatype float64.Hence, it gets converted into a tensor of elements with datatype float64.

So, it is important that in order to use this with the other tensors that are probably being created in PyTorch and hence, default to datatype float32, We should convert the datatype of the tensor elements to float32 before using it anywhere

In [ ]:
tensor = tensor.type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Converting tensor back into numpy array
numpy_array_rev = tensor.numpy()
numpy_array_rev, numpy_array_rev.dtype

(array([[-0.9461523 , -0.20137593],
        [ 0.93020964,  0.1082124 ]], dtype=float32),
 dtype('float32'))

In [ ]:
# We can convert this numpy_array_rev into float64
numpy_array_rev = np.float64(numpy_array_rev)
numpy_array_rev.dtype

dtype('float64')

## 6. Checking which device the model and data is on : cuda or cpu?

In [7]:
import torch
from torch import nn

device = "cuda" if torch.cuda.is_available() else "cpu"

model_0 = nn.Sequential(
    nn.Linear(in_features=2, out_features=1)
).to(device)

model_0

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)

In [9]:
# This gives the device the model is on
next(model_0.parameters()).device

device(type='cuda', index=0)

In [15]:
x = torch.arange(1,10,1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
if x.get_device()==-1:
  print("cpu")
elif x.get_device()==0:
  print("cuda")

cpu


In [17]:
x = x.to(device)

In [18]:
if x.get_device()==-1:
  print("cpu")
elif x.get_device()==0:
  print("cuda")

cuda
